<a href="https://colab.research.google.com/github/TayTT/MATMU/blob/main/Kopia_notatnika_nw_skarbek_affine_fit_pl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

copyright 2020: *Władysław Skarbek, Warsaw University of Technology*<br>
(Jupyter notebook addressed to students of: EADIR, GSN, MATMU)
$\newcommand{\xx}[2]{(#1)(#2)}$
$\newcommand{\bb}[1]{\mathbb{#1}}$
$\newcommand{\cl}[1]{\mathcal{#1}}$
$\newcommand{\tp}[1]{{#1}^{\intercal}}$
$\newcommand{\tr}[1]{\text{trace}\left[#1\right]}$
$\newcommand{\inv}[1]{\in\bb{R}^{#1}}$
$\newcommand{\inm}[2]{\in\bb{R}^{#1\times#2}}$
$\newcommand{\invc}[1]{\in\bb{C}^{#1}}$
$\newcommand{\inmc}[2]{\in\bb{C}^{#1\times#2}}$
$\newcommand{\rbox}[2]{\mathrel{\raise{#1}{#2}}}$
$\newcommand{\xconv}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{2.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{C}}\kern{-6.5pt}\raise{4.5pt}{{\tiny{#5}}}\end{array}
\kern{0pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{2.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xdense}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{F}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xpool}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-3pt}
\begin{array}[]{l}{\LARGE\bb{P}}\kern{-6.5pt}\raise{0.8pt}{{\tiny{#5}}}\end{array}
\kern{0pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xinp}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\cl{I}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xdrop}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{D}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{0.5pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xmerge}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{M}}\kern{-4.5pt}\raise{1.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\newcommand{\xgeneral}[5]{
\begin{array}[]{r}{\tiny{#4\ }}\\\raise{1.5pt}{{\tiny{#3}}}\end{array}
\kern{-4pt}
\begin{array}[]{l}{\LARGE\bb{Q}}\kern{-9.0pt}\raise{4.5pt}{{\tiny{#5}}}\end{array}
\kern{2pt}
\begin{array}[]{l}{\tiny {#2}}\\\raise{1.5pt}{{\tiny{#1}}}\end{array}}$
$\def\ds{\displaystyle}$
$\def\ass{\leftarrow}$
$\def\od#1#2{\nabla_{#2}#1}$
$\def\tod#1#2{\tp{\nabla}_{#2}{#1}}$
$\def\cl#1{{\cal#1}}$
$\def\mbm#1{\mathbf{#1}}$
$\def\sp#1#2{\frac{\partial{#1}}{\partial{#2}}}$
$\def\spp#1#2#3{\frac{\partial{#1}}{\partial{#2}\partial{#3}}}$
$\def\eqd{\doteq}$
$\def\ra{\rightarrow}$
$\def\lra{\longrightarrow}$
$\def\ovra#1{\overset{#1}{\lra}}$
$\def\dra{\overset{\circ}{\lra}}$
$\def\xeq#1{\overset{#1}{=}}$
$\def\ov#1{\overline{#1}}$
$\def\dotp#1#2{\left\langle#1,#2\right\rangle}$
$\def\th#1{\ov{#1}^{\intercal}}$
$\def\rv#1{\widetilde{#1}}$
$\def\vars#1#2{\mathtt{var}_{#1}{\left[#2\right]}}$
$\def\pmodd#1{\kern{-1mm}\pmod{#1}}$
$\def\pdt#1#2#3{\frac{\partial^2 #1}{\partial #2\partial #3}}$
$\def\diag#1{\mathtt{diag}\left[#1\right]}$
$\def\rank#1{\mathtt{rank}\left[#1\right]}$
$\def\span#1{\mathtt{span}\left[#1\right]}$
$\def\spann#1{\mathtt{span}\left[#1\right]}$
$\def\tr#1{\mathtt{tr}\left[#1\right]}$
$\def\var#1{\mathtt{var}\left[#1\right]}$
$\def\kernn#1{\kern{#1pt}}$
$\def\raisee#1#2{\raise{#1}{#2}}$
$\def\colorr#1#2{\color{#1}{#2}}$
$\def\wtt{\ \text{ wtt }\ }$
$\def\mbm#1{\mathbf{#1}}$


# Matematyka afinicznego dopasowania

W szczególności narzędzia stosowane w dopasowaniu chmur punktów w $R^d$.

###Dekompozycja EVD

Powtórka z elementów klasycznej algebry liniowej $-$ wiek XIX.

####Wartość własna $-$ definicja spektrum macierzy

*Spektrum* macierzy zespolonej $C\inmc{n}{n}$ stanowi zbiór liczb zespolonyc $\lambda(C)\subset\bb{C}$ zdefiniowany następująco:
$
\lambda(C) \eqd \{\lambda\in\bb{C}: \det(C-\lambda I_n)=0\}
$
- Funkcję  $p(\lambda)\eqd\det(C-\lambda I_n)$ nazywamy *wielomianem charakterystycznym macierzy* $C.$
- *Spektrum jest zawsze zbiorem skończonym:*:<br>Jeśli $C\inmc{n}{n}$, to $\left|\lambda(C)\right|\leq n.$
- Elementy spektrum macierzy nazywamy jej *wartościami własnymi*: $\lambda\in\lambda(C)$ wtedy i tylko wtedy gdy $\exists u\invc{n}, Cu=\lambda u.$
- Wektor $u$ skalowany w transformację $C$ przez czynnik $\lambda$ nazywamu *wektorem własnym* macierzy $C$ określonym dla wartości własnej $\lambda.$
- Każda wartość własna określa *podprzestrzeń własną*:<br>
Jesli $\lambda\in\lambda(C)$, to zbiór $\cl{E}_{\lambda}\eqd\{u: Cu=\lambda u\}$ jest podprzestrzenią liniową w przestrzeni $\bb{C}^n.$



####Obliczanie wartości własnych w pakiecie `sympy`

#####Wielomian w reprezentacji symbolicznej: rozwijanie, wyznaczniki, pierwiastki

In [1]:
import sympy as sym
x = sym.Symbol('x'); y = sym.Symbol('y')
print(sym.expand((x + y) ** 3))
print(sym.expand((x-1)*(x+1)))

x**3 + 3*x**2*y + 3*x*y**2 + y**3
x**2 - 1


In [2]:
As = sym.Matrix([[1,2],[3,4]])
xI = sym.Matrix([[x,0],[0,x]])
ex = sym.expand(xI-As); print(ex)
d = ex.det(); print(d)
p = sym.expand(d); print(p)
roots = sym.nroots(p)
roots

Matrix([[x - 1, -2], [-3, x - 4]])
x**2 - 5*x - 2
x**2 - 5*x - 2


[-0.372281323269014, 5.37228132326901]

#####Wartość własna $-$ algorytm symboliczny versus algorytm numeryczny

In [3]:
import numpy as np
from numpy.linalg import eig, svd, norm, cholesky

In [4]:
A = np.array([[1,2],[3,4]])
ls,vs = eig(A)
A, ls, vs, np.dot(A,vs[:,0]), ls[0]*vs[:,0], ls, roots, ls-roots

(array([[1, 2],
        [3, 4]]),
 array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]),
 array([ 0.30697009, -0.21062466]),
 array([ 0.30697009, -0.21062466]),
 array([-0.37228132,  5.37228132]),
 [-0.372281323269014, 5.37228132326901],
 array([0, 0], dtype=object))

Wektory własne $-$ testujemy spełnienie własności definicyjnej

In [5]:
A = np.array([[1,-2,3],[-4,5,6],[7,8,-9]])
ls, vs = eig(A)
A, ls, vs, np.dot(A,vs[:,2]), ls[2]*vs[:,2]

(array([[ 1, -2,  3],
        [-4,  5,  6],
        [ 7,  8, -9]]),
 array([-13.76691494,   2.78453226,   7.98238268]),
 array([[ 0.23127389,  0.84043331, -0.09343993],
        [ 0.34064779,  0.05826955,  0.91498738],
        [-0.91130208,  0.53877315,  0.3925138 ]]),
 array([-0.7458733 ,  7.30377939,  3.13319532]),
 array([-0.7458733 ,  7.30377939,  3.13319532]))

#### Problem własny w przypadku macierzy symetrycznych

- *Transpozycja* $\tp{C}$ macierzy zespolonej $C\inmc{m}{n}$  w definicji po-elementowej:
$
(\tp{C})_{ij}\eqd C_{ji},\ i=1,\dots,m,\ j=1,\dots,n
$
- Definicja: Macierz $C\inmc{m}{n}$ jest *symetryczna*  wtedy i tylko wtedy gdy $\tp{C}=C.$
- Własność: Jeśli $C\inmc{m}{n}$ jest symetryczna, to $m=n$ oraz  $C\inm{n}{n}$.
- *Sprzężona transpozycja* $\th{C}$ macierzy zespolonej $C$  w definicji po-elementowej:
$
(\th{C})_{ij}\eqd \ov{C}_{ji},\ i,j=1,\dots,n
$
- $C$ jest *Hermitowska* wtedy i tylko wtedy gdy $\th{C}=C.$
- Własność: Spektra macierzy symetrycznej i macierzy Hermitowskiej są podzbiorami zbioru liczb rzeczywistych:<br>
Jesli $C=\tp{C}$ lub $C=\th{C}$, to $\lambda(C)\subset\bb{R}$
- Własność: Dla różnych wartości własnych mamy *ortogonalność wektorów własnych*:<br>
Jeśli $Cu_i=\lambda_i u_i,\ Cu_j=\lambda_j u_j$ oraz $\lambda_1\neq\lambda_2$, to $\tp{u}_iu_j=0$ w przypadku symetrycznej macierzy $C$ oraz $\th{u}_iu_j=0$ w przypadku macierzy Hermitowskiej.
- Własność: Z każda macierzą symetryczną lub macierzą Hermitowską $C$ możemy związać *bazę ortogonalną* złożoną wyłącznie z wektorów własnych:<br>
Niech $\mathtt{obase}(\cl{S})$ oznacza ortogonalną bazę w liniowej podprzestrzenie $\cl{S}.$ Wtedy baza dla całej przestrzeni może być sumą mnogościową baz dla podprzestrzeni własnych wszystkich wartości własnych:
$$\ds
\mathtt{obase}\left(\bb{C}^n\right) \eqd \bigcup_{\lambda\in\lambda(C)}\mathtt{obase}\left(\cl{E}_{\lambda}\right)
$$


####Dekompozycja EVD

Niech ortogonalna baza wektorów własnych symetrycznej lub Hermitowskiej macierz $C\inmc{n}{n}$ tworzy kolumny macierzy $U\inmc{n}{n}$ zapisane według malejącego ciągu wartości własnych:
$$
\begin{array}{l}
Cu_i = \lambda_iu_i,\ i=1,\dots,n\\[5pt]
U \eqd [u_1,\dots,u_n],\ \lambda_1\geq\dots\geq\lambda_n,\
\Lambda \eqd \diag{\lambda_1,\dots,\lambda_n}
\end{array}
$$

*Dekompozycja EVD* (EigenValue Decomposition) macierzy $C\overset{evd}{=}U\Lambda\th{U}$ wynika z własności ortogonalności bazy własnej, a więc i macierzy własnej $U$:<br>
Dekompozycja EVD jest treścią tzw. twierdzenia spektralnego:
Dla macierzy symetrycznej symmetric $C\inm{n}{n}$ oraz dla macierzy hermitowskiej $C\inmc{n}{n}$
$$
C = U\Lambda\th{U} = \sum_{i=1}^n\lambda_iu_i\th{u}_i
$$


In [6]:
B = np.dot(A,A.T)
eigvals, eigvecs = eig(B)
print(B, '\n', np.dot(np.dot(eigvecs,np.diag(eigvals)),eigvecs.T))

[[ 14   4 -36]
 [  4  77 -42]
 [-36 -42 194]] 
 [[ 14.   4. -36.]
 [  4.  77. -42.]
 [-36. -42. 194.]]


###Macierze nieujemnie określone

*Definicje*:
- Jeśli  $A\inm{n}{n}$ oraz  $\tp{A}=A$ to $A$ jest nieujemnie określona wtedy i tylko wtedy gdy $\tp{x}Ax\geq 0$ dla dowolnego $x\inv{n}.$
- Jeśli  $A\inmc{n}{n}$ oraz  $\th{A}=A$ to $A$ jest nieujemnie określona wtedy i tylko wtedy gdy $\th{x}Ax\geq 0$ dla dowolnego $x\invc{n}.$


*Własności*

- W symetrycznej i nieujemnie określonej macierzy $A\inm{n}{n}$, wektory własne o różnych wartościach własnych są wzajemnie prostopadłe, tj. gdy $\tp{A}=A, \forall x\inv{n}\tp{x}Ax\geq 0$:
$$
\left[Au=\lambda u,\ Au'=\lambda' u',\ \lambda'\neq\lambda\right] \lra \tp{u}u' = 0
$$
- W przypadku nieujemnie okreslonej macierzy Hermitowskiej, tj. gdy $\th{A}=A, \forall x\inv{n}\th{x}Ax\geq 0$:
$$
\left[Au=\lambda u, Au'=\lambda' u',\ \lambda'\neq\lambda\right] \lra \th{u}u' = 0
$$
- Jeśli $B\inm{m}{n}$, to macierze $\tp{B}B$ oraz $B\tp{B}$ są symetryczne i nieujemnie określone.
- Jeśli $C\inmc{m}{n}$, to macierze $\th{C}C$ oraz $C\th{C}$ są Hermitowskie i nieujemnie określone.
- Jeśli $A\inm{m}{n}$, to spektra macierzy $A\tp{A}$ oraz $\tp{A}A$ są identyczne i co więcej wektory własne odpowiadają sobie wzajemnie w odwzorowaniach $\tp{A}$ oraz $A$, odpowiednio.
$$
\begin{array}{l}
A\tp{A}u = \lambda u \lra \tp{A}A\underbrace{(\tp{A}u)}_v = \lambda\underbrace{(\tp{A}u)}_v\\
\tp{A}Av = \lambda v \lra A\tp{A}\underbrace{(Av)}_u = \lambda\underbrace{(Av)}_u
\end{array}
$$
- Jeśli $A\inmc{m}{n}$, to spektra macierzy $A\th{A}$ oraz $\th{A}A$ są identyczne, co więcej wektory własne odpowiadają sobie wzajemnie w odwzorowaniach $\th{A}$ oraz $A$, odpowiednio.
$$
\begin{array}{l}
A\th{A}u = \lambda u \lra \th{A}A\underbrace{(\th{A}u)}_v = \lambda\underbrace{(\th{A}u)}_v\\[5pt]
\th{A}Av = \lambda v \lra A\th{A}\underbrace{(Av)}_u = \lambda\underbrace{(Av)}_u
\end{array}
$$


- Jeśli wektory własne $u,u'$ macierzy $A\tp{A}$ są prostopadłe, to ich odpowiedniki $v\eqd\tp{A}u$ oraz $v'\eqd\tp{A}u'$  są też prostopadłe:
$$
\begin{array}{l}
\left[A\tp{A}u = \lambda u,\ v\eqd\tp{A}u,\ A\tp{A}u' = \lambda' u',\ v'\eqd\tp{A}u'\ \tp{u}u'=0\right]\\
\lra \tp{v}v'=\tp{u}(A\tp{A}u') = \lambda'(\tp{u}u') = 0
\end{array}
$$
- Jeśli wektory własne $u,u'$ macierzy $A\th{A}$ są prostopadłe, to ich odpowiedniki $v\eqd\th{A}u$ oraz $v'\eqd\th{A}u'$  są też prostopadłe:
$$
\begin{array}{l}
\left[A\th{A}u = \lambda u,\ v\eqd\th{A}u,\ A\th{A}u' = \lambda' u',\ v'\eqd\th{A}u',\ \th{u}u'=0\right]\\
\lra \th{v}v'=\th{u}(A\th{A}u') = \lambda'(\th{u}u') = 0
\end{array}
$$

### M23L: Zadanie EVD-S

Na przykładzie losowej symetrycznej macierzy $A\inm{4}{4}$ porównaj symboliczne rozwiązanie problemu własnego z rozwiązaniem numerycznym.

In [92]:
import sympy as sym
import numpy as np

x = sym.Symbol('x')

# Losowa macierz 4x4 z ograniczonym zakresem
A = np.random.randint(-10, 10, size=(4, 4))
A = (A + A.T) / 2
As = sym.Matrix(A)

xI = sym.diag(x, x, x, x)
ex = sym.expand(xI - As)
d = ex.det()
p = sym.expand(d)

# Rozwiązanie symboliczne
roots = sym.nroots(p, n=9)
print("Rozwiązanie symboliczne:", roots)

# Rozwiązanie numeryczne
ls, vs = np.linalg.eig(A)
print("Rozwiązanie numeryczne:", ls)




Rozwiązanie symboliczne: [-14.8201021, -5.97058318, 3.32565586, 8.46502942]
Rozwiązanie numeryczne: [-14.82010211   8.46502942   3.32565586  -5.97058318]


### SVD (Singular Value Decomposition) $-$ dekompozycja na macierze singularne

*Twierdzenie SVD*

Jeśli $A\inm{m}{n}$, to istnieją znormalizowane macierze ortogonalne $U\inm{m}{m}$, $V\inm{n}{n}$, oraz macierz diagonalna $\Sigma\inm{m}{n}$ takie, że:
$$
\begin{array}{l}
A \overset{svd}{=} U\Sigma\tp{V} = U_r\Sigma_r\tp{V}_r = \ds\sum_{i=1}^r\sigma_iu_i\tp{v}_i\\
\tp{A} \overset{svd}{=} V\tp{\Sigma}\tp{U} = V_r\Sigma_r\tp{U}_r =  \ds\sum_{j=1}^r\sigma_jv_j\tp{u}_j\\
U\inm{m}{m},\ \tp{U}U=I_m,\ V\inm{n}{n},\ \tp{V}V=I_n\ -\ \text{warunki znormalizowanej ortogonalności}\\
U=[\underbrace{u_1,\dots,u_r}_{U_r},\underbrace{u_{r+1},\dots,u_m}_{U_{r:}}],\ u_i\inv{m},\ i=1,\dots,m\\
V=[\underbrace{v_1,\dots,v_r}_{V_r},\underbrace{v_{r+1},\dots,v_n}_{V_{r:}}],\ v_j\inv{m},\ j=1,\dots,n\\
\lra U=[U_r,U_{r:}],\ V=[V_r,V_{r:}]\\
r=\rank{A}, \sigma_1\geq\sigma_2\geq\dots\geq\sigma_r>0\ -\ \text{dodatnie wartości singularne}\\
\Sigma_r \eqd \diag{\sigma_1,\dots,\sigma_r}
\lra
\Sigma = \left[
  \begin{array}{cc}
  \Sigma_r & 0_{r\times(n-r)}\\
  0_{(m-r)\times r} & 0_{(m-r)\times(n-r)}
  \end{array}
\right]
\end{array}
$$



*Uwaga:* Jesli zastąpimy transpozycję macierz przez transpozycję ze sprzężeniem, to powyższe twierdzenie SVD jest prawdziwe również dla macierzy zespolonych $A\inmc{m}{n}$.

*Dowód twierdzenia SVD* na podstawie dekompozycji na macierze wektorów własnych.

1. Realizujemy dekompozycje EVD dla macierzy $A\tp{A}$:
$$
r = \rank{A},\ A\tp{A} \overset{evd}{=} U\Lambda\tp{U} \lra A\tp{A}U = U\Lambda
\lra A\tp{A}U_r = U_r\Lambda_r
$$
1. Na podstawie znormalizowanej ortogonalnej bazy własnej $U_r$, uzyskanej dla macierzy $A\tp{A}$ dobieramy najpierw ortogonalną bazę własną dla macierzy $\tp{A}A$, a następnie ją normalizujemy:
$$
V'_r\eqd \tp{A}U_r,\ V_r\eqd V_r'\Lambda_r^{-\frac{1}{2}}=\tp{A}U_r\Lambda_r^{-\frac{1}{2}} \lra \tp{A}AV_r = V_r\Lambda_r
$$
1. *Wniosek*: $\tp{U}_rAV_r=\Lambda_r^{\frac{1}{2}}$
$$
V_r\eqd \tp{A}U_r\Lambda_r^{-\frac{1}{2}} \lra  \tp{U}_rAV_r = \tp{U}_rA\tp{A}U_r\Lambda_r^{-\frac{1}{2}} = \tp{U}_rU_r\Lambda_r\Lambda_r^{-\frac{1}{2}}=\Lambda_r^{\frac{1}{2}}
$$
1. Bazy $U_r$, $V_r$ dla podprzestrzeni uzupełniamy do pełnych znormalizowanych i ortogonalnych baz. W przypadku $U_{r:}$ jest już znane z EVD, a w przypadku $V_{r:}$ istnienie takiego rozszerzenia wynika np. z konstrukcji Grama-Schmidta:
$$
\begin{array}{l}
\underbrace{
\left[
\begin{array}{c}
\tp{U}_r\\
\tp{U}_{r:}
\end{array}
\right]
}_{\tp{U}}
A
\begin{array}{l}
\underbrace{
\left[
V_r,\ V_{r:}
\right]
}_{V}
\end{array}
\end{array}
=
\left[
\begin{array}{cc}
\tp{U}_rAV_r & \tp{U}_rAV_{r:}\\
\tp{U}_{r:}AV_r & \tp{U}_{r:}AV_{r:}
\end{array}
\right]
=
\underbrace{
\left[
\begin{array}{cc}
\Lambda_r^{\frac{1}{2}} & 0_{r\times(n-r)}\\
0_{(m-r)\times r} & 0_{(m-r)\times(n-r)}
\end{array}
\right]
}_{\Sigma}
$$
1. Otrzymaliśmy równanie macierzowe typu $\tp{U}AV=\Sigma$, które mnożymy lewostronnie i prawostronnie przez odwrotności macierzy ortogonalnych $\left(\tp{U}\right)^{-1}=U$ oraz $V^{-1}=\tp{V}:$
$$
\begin{array}{l}
\tp{U}AV=\Sigma \lra \left(\tp{U}\right)^{-1}\tp{U}AVV^{-1}=\left(\tp{U}\right)^{-1}\Sigma V^{-1}\\
 \lra A \overset{svd}{=} U\Sigma\tp{V},\ \text{ gdzie}\\
U \eqd \left[
U_r,\ U_{r:}
\right]
,\
\Sigma \eqd
\left[
\begin{array}{cc}
\Lambda_r^{\frac{1}{2}} & 0_{r\times(n-r)}\\
0_{(m-r)\times r} & 0_{(m-r)\times(n-r)}
\end{array}
\right],\
V \eqd \left[
V_r,\ V_{r:}
\right]
\end{array}
$$
1. Gdy wykonamy mnożenie blokowe w wyrażeniu $U\Sigma\tp{V}$, podstawiając $\Sigma_r\eqd\Lambda_r^{\frac{1}{2}}$, otrzymamy zredukowaną postać SVD:
$$
A = U\Sigma\tp{V} = \left[
U_r,\ U_{r:}
\right]
\left[
\begin{array}{cc}
\Sigma_r & 0_{r\times(n-r)}\\
0_{(m-r)\times r} & 0_{(m-r)\times(n-r)}
\end{array}
\right]
\left[
\begin{array}{c}
\tp{V}_r\\
\tp{V}_{r:}
\end{array}
\right]
= U_r\Sigma_r\tp{V}_r
$$
1. Gdy na postaci zredukowanej dokonamy rozwinięcia (na podstawie ogólnego twierdzenia o iloczynach zewnętrznych macierzy i ich kolumn) oraz uwzględnimy oznaczenie $\sigma_i\eqd\sqrt{\lambda}_i$, to otrzymamy:
$$
A \overset{svd}{=} U\Sigma\tp{V} = U_r\Sigma_r\tp{V}_r = \sum_{i=1}^r\sigma_iu_i\tp{v}_i\quad\Box
$$

*Wnioski* (SVD macierzy danych a charakterystyczne liniowe bazy)
1. $U=[u_1,\dots,u_m]$ jest znormalizowaną ortogonalną bazą w przestrzeni $\bb{R}^m$, tj.
$$ x\inv{m}\lra x = U(\tp{U}x) = \ds\sum_{i=1}^m(\tp{u_i}x)u_i$$
1. $U_r=[u_1,\dots,u_r]$ jest znormalizowaną ortogonalną bazą w podprzestrzeni $\span{A}\subseteq\bb{R}^m$.
1. $U_{r:}=[u_{r+1},\dots,u_m]$ jest znormalizowaną ortogonalną bazą w podprzestrzeni $\ker{[\tp{A}]}\subset\bb{R}^{m}$.
1. $V=[v_1,\dots,v_n]$ jest znormalizowaną ortogonalną bazą w przestrzeni $\bb{R}^n$, tj.
$$ x\inv{n}\lra x = V(\tp{V}x) = \ds\sum_{j=1}^n(\tp{v_j}x)v_j$$
1. $V_r=[v_1,\dots,v_r]$ jest znormalizowaną ortogonalną bazą w podprzestrzeni $\span{\tp{A}}\subseteq\bb{R}^n$.
1. $V_{r:}=[v_{r+1},\dots,v_n]$ jest znormalizowaną ortogonalną bazą w podprzestrzeni $\ker{[A]}\subset\bb{R}^n$.




In [7]:
s2,U = eig(np.dot(A,A.T))
s3,V = eig(np.dot(A.T,A))
print(s2,s3,'\n',U,'\n',V)
U2,s,V2t = svd(A)
print(s*s,'\n',U2,'\n',V2t.T)

[213.8312464   6.8032865  64.3654671] [213.8312464   6.8032865  64.3654671] 
 [[ 0.17517411  0.977064   -0.12107839]
 [ 0.29357441  0.06554757  0.95368631]
 [-0.93974895  0.20260667  0.27535875]] 
 [[-0.51818244 -0.81781672 -0.25032533]
 [-0.43769958  0.00212276  0.89911877]
 [ 0.73478298 -0.57547486  0.35905802]]
[213.8312464  64.3654671   6.8032865] 
 [[ 0.17517411  0.12107839 -0.977064  ]
 [ 0.29357441 -0.95368631 -0.06554757]
 [-0.93974895 -0.27535875 -0.20260667]] 
 [[-0.51818244  0.25032533 -0.81781672]
 [-0.43769958 -0.89911877  0.00212276]
 [ 0.73478298 -0.35905802 -0.57547486]]


###Dekompozycja Choleskiego

Jeśli $B\inm{n}{n}$ jest macierzą symetryczną, nieujemnie określoną, to istnieje dolno-trókątna macierz $X\inm{n}{n}$ taka, że $B=X\tp{X}.$

In [8]:
B = np.dot(A,A.T)
X = cholesky(B)
print(B,'\n',X,'\n',np.dot(X,X.T))

[[ 14   4 -36]
 [  4  77 -42]
 [-36 -42 194]] 
 [[ 3.74165739  0.          0.        ]
 [ 1.06904497  8.70960061  0.        ]
 [-9.62140471 -3.64130195  9.3898611 ]] 
 [[ 14.   4. -36.]
 [  4.  77. -42.]
 [-36. -42. 194.]]


###Uogólniony problem Procrustesa

Uogólniony problem Procrustesa dotyczy optymalnego dopasowania źródłowej bryły 3D do bryły docelowej, gdy w procesie dopasowania dysponujemy dowolnymi transformacjami afinicznymi.

W zastosowaniach związanych z identyfikacją modelu 3D, najczęściej zamiast bryły 3D, mamy zbiór punktów 3D, tzw. chmurę punktów.

W terminach matematycznych możemy ten problem wyrazić jako klasyczny problem najmniejszych kwadratów:
- mając źródłową chmurę punktów $C\inm{3}{N}$ i docelową chmurę punktów $C'\inm{3}{N}$,
- mamy ustalić macierz obrotu $R\inm{3}{3}$, współczynnik skalowania $s\in\bb{R}_+$ oraz wektor przesunięcia $b\inv{3}$, tak by
- zminimalizować miarę niedopasowania:
$$\boxed{\cl{E}(R,s,b) \eqd \left\|sRC+b\tp{1}_N-C'\right\|^2}$$.

Powyższy problem optymlizacyjny nazywamy *uogólnionym problemem Procustesa*. Problem ten ma ogólne rozwiązanie oparte na dekompozycji SVD dla macierzy $\ov{C}'\tp{\ov{C}}\overset{svd}{=}U\Sigma\tp{V}$, gdzie $\ov{C}\eqd C-\ov{c}\tp{1}_N$ jest operatorem centrowania chmury punktów, tj. takiej relokacji chmury punktów, by jej centroid $\ov{c}\eqd\ds\frac{1}{N}\sum_{i\in[N]}c_i,$ znalazł się w początku układu współrzędnych.


###Rozwiązanie ogólnego problemu Procrustesa

Następujące formuły podaja jedyne optymalne rozwiązanie problemu Procrustesa, gdy chmury punktów $C, C'\inm{M}{N}$ leżą w przestrzeni dowolnego wymiaru $M$:
$$
\ov{C}'\tp{\ov{C}}\overset{svd}{=}U\Sigma\tp{V}
\ds \longrightarrow \left[\ds
R^{\ast} \ass U\tp{V},\  s^{\ast} \ass \ds
\frac{\tr{\Sigma}}{\tr{\ov{C}\tp{\ov{C}}}}=
\frac{\ds\sum_{i\in[M]}\sigma_i}{\|\ov{C}\|^2},\ b^{\ast} \ass \ov{c}'-s^{\ast}R^{\ast}\ov{c}\right]
$$

*Uwaga:* Wzory na optymalne parametry się nie zmienią, gdy rozważymy macierz kowariancji $Cov(C',C)\eqd\frac{1}{N}\ov{C}'\tp{\ov{C}}$ między zbiorami punktów $C'$ oraz $C$, bo w efekcie $\sigma_i'=\frac{\sigma_i}{N}$, a jednocześnie stała działa normalizacyjnie na  obie chmury jako mnożenie przez czynnik $\frac{1}{\sqrt{N}}$:
$$
\begin{array}{l}
Cov(C',C)\eqd\frac{1}{N}\ov{C}'\tp{\ov{C}} = \left(\frac{\ov{C}'}{\sqrt{N}}\right)\left(\frac{\tp{\ov{C}}}{\sqrt{N}}\right)
\overset{svd}{=}U\underbrace{\left(\frac{\Sigma}{N}\right)}_{\Sigma'}\tp{V}\\
\ds \longrightarrow \left[\ds
R^{\ast} \ass U\tp{V},\  s^{\ast} \ass
\frac{\tr{\Sigma'}}{\tr{Cov(C,C)}}=
\ds\frac{\ds\sum_{i\in[M]}\frac{1}{N}\sigma_i}{\left\|\frac{1}{\sqrt{N}}\ov{C}\right\|^2}=\frac{\ds\sum_{i\in[M]}\sigma_i}{\|\ov{C}\|^2}\right]
\end{array}
$$

####Interpretacja statystyczna rozwiązania Procrustes
1. Znaleziony optymalny ruch afiniczny transformuje punkt średni (centroid) źródłowego zbioru punktów na punkt średni (centroid) docelowego  zbioru punktów.
1. Optymalne skalowanie $s^{\ast}$ jest ilorazem kowariancji wzajemnej między zbiorem źródłowym a zbiorem docelowym a wariancją zbioru źródłowego.
1. Optymalna macierz obrotu $R^{\ast}$ mapuje wierszową singularną bazę $V$ macierzy kowariancji $cov(C',C)$ na jej kolumnową singularną bazę $U$.

#### M23L: Pytanie (o Procrustesa)

Kim był Procrustes? Czy transformacje, których się imał były afiniczne?


Prokrustes, znany również jako Prokrustes z Attiki, był postacią z mitologii greckiej. Był on właścicielem gospody, w której gościł podróżnych. Jednak jego gościnność była podstępna. Prokrustes miał zwyczaj poddawać swoich gości brutalnym przekształceniom, aby dopasować ich do swoich łóżek. Miał dwie łóżka: jedno zbyt krótkie dla wysokich gości i drugie zbyt długie dla niskich gości. Aby dostosować długość ciała podróżnych do rozmiaru łóżka, Prokrustes stosował przemoc, cięcie lub rozciąganie ciał.

Transformacje, których Prokrustes używał, nie były afiniczne. Transformacje afiniczne to takie przekształcenia, które zachowują proporcje i linie proste. Natomiast Prokrustes dokonywał przemocy i brutalnych manipulacji ciałem gości, co nie jest charakterystyczne dla przekształceń afinicznych. Były to przekształcenia nieliniowe, które miały na celu dopasowanie ciała gości do konkretnych rozmiarów jego łóżek, niezależnie od tego, czy byli zbyt wysocy czy zbyt niscy.

#### Ćwiczenie (Funkcja kosztu - od normy do sumy kwadratów błędów dopasowania)

Niech macierze punktów $C,C'\inm{3}{N}$ będą w analizie funkcji strat zastąpione przez sekwencje punktów $c_i,c'_i$:
$$C=[c_0,c_1,\dots,c_{N-1}],\quad C'=[c'_0,c'_1,\dots,c'_{N-1}]$$
Przedstaw funkcję strat $\cl{E}(R,s,b) \eqd \left\|sRC+b\tp{1}_N-C'\right\|^2$ w postaci sumy:
$$
\cl{E}(R,s,b) = \sum_{i=0}^{N-1}\|???-c'_i\|^2
$$

####Funkcja `generalProcrustes`

In [9]:
def cov_stats(X,Y): # X,Y shape: M x N, here M = 3
  M,N = X.shape
  xb = np.mean(X,axis=1); yb = np.mean(Y,axis=1)
  Xb = (X.T-xb).T; Yb = (Y.T-yb).T
  Cov_XX = np.dot(Xb,Xb.T)/N
  Cov_XY = np.dot(Xb,Yb.T)/N
  Cov_YX = np.dot(Yb,Xb.T)/N
  Cov_YY = np.dot(Yb,Yb.T)/N
  return xb, yb, Cov_XX, Cov_XY, Cov_YX, Cov_YY

In [10]:
def generalProcrustes(X,Y):
  xb, yb, Cov_XX, Cov_XY, Cov_YX, Cov_YY = cov_stats(X,Y)
  U,sigmas,Vt = svd(Cov_YX)
  R_ast = np.dot(U,Vt)
  s_ast = np.sum(sigmas)/np.trace(Cov_XX)
  b_ast = yb-s_ast*np.dot(R_ast,xb)
  return R_ast, s_ast, b_ast

#### M23L: Zadanie (testowanie funkcji `generalProcrustes`)

Niech $C\inm{3}{1000}$ będzie chmurą punktów o $n=1000$ punktów w przestrzeni 3D generowaną losowo według rozkładu Gaussa. Obracamy, skalujemy i przesuwamy tę chmurę zgodnie z formułami:
$$
c'_i =
3\cdot
\left[
\begin{array}{ccc}
\frac{\sqrt{3}}{2} & -\frac{1}{2} & 0\\
\frac{1}{2} & \frac{\sqrt{3}}{2} & 0\\
0 & 0 & 1
\end{array}
  \right]
  c_i +
\left[
\begin{array}{c}
1\\
0\\
-1
\end{array}
  \right],\ i=0,\dots,999
$$
Na tych danych sprawdzono poprawność twierdzenia Procrustesa (patrz rozwiązanie poniżej).

Twoim zadaniem jest sprawdzenie twierdzenia Procrustesa na następujących, innych danych:

$$
c'_i =
3\cdot
\left[
\begin{array}{ccc}
\frac{1}{2} & \frac{\sqrt{3}}{2} & 0\\
-\frac{\sqrt{3}}{2} & \frac{1}{2} & 0\\
0 & 0 & 1
\end{array}
  \right]
  c_i +
\left[
\begin{array}{c}
-1\\
0\\
1
\end{array}
  \right],\ i=0,\dots, 999
$$


**Rozwiązanie**

*Definiujemy transformację afiniczną*

In [11]:
s = 3
b = np.array([1,0,-1.])
sq3 = np.sqrt(3)
R = np.array([[sq3/2,-1/2,0],[1/2,sq3/2,0],[0,0,1]])

In [32]:
print("Sprawdzenie dla innych danych.")
s = 3
b = np.array([-1, 0, 1])
sq3 = np.sqrt(3)
R = np.array([[1/2, sq3/2,0],
              [-sq3/2, 1/2 ,0],
              [0, 0, 1]])

Sprawdzenie dla innych danych.


*Sprawdzamy ortogonalność*

In [34]:
print('Orthogonal?:\n',np.dot(R.T,R))

Orthogonal?:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


*Generujemy losową chmurę i ją centrujemy*

In [35]:
from numpy.linalg import det,svd,norm
from numpy.random import randn

In [36]:
C = randn(3,100); c_avg = np.average(C,axis=1)
C = C-np.outer(c_avg,np.ones(100)); c_avg = np.average(C,axis=1)
print('Is centered?:',c_avg)

Is centered?: [-7.21644966e-18  4.32986980e-17  1.11022302e-17]


*Stosujemy transformację afiniczną*

W efekcie mamy dwie chmury punktów: wejściową $C\inm{3}{100}$ i wyjściową $C'\inm{3}{100}$.

In [37]:
Cp = s*np.dot(R,C)+np.outer(b,np.ones(100))

*Implementujemy w sposób jawny rozwiązanie problemu Procrustesa*

In [38]:
cb = np.mean(C,axis=1); cpb = np.mean(Cp,axis=1)
Cb = (C.T-cb).T; Cpb = (Cp.T-cpb).T
U,Sigma,Vt = svd(np.dot(Cpb,Cb.T))
R_star = np.dot(U,Vt)
s_star = np.sum(Sigma)/np.sum(Cb*Cb)
b_star = np.average(Cp,axis=1)

*Sprawdzamy zidentyfikowane parametry transformacji*

In [39]:
print('R-R_star:',R-R_star)
print('error for rotation matrix ||R-R_star||:',norm(R-R_star))
print('error for scale = |s-s_star|:',abs(s-s_star))
print('error for shift = ||b-b_star||:',norm(b-b_star))

R-R_star: [[-4.44089210e-16  0.00000000e+00  2.71616187e-17]
 [ 5.55111512e-16  5.55111512e-17 -1.44384151e-16]
 [-4.81548234e-17  1.09298465e-17 -4.44089210e-16]]
error for rotation matrix ||R-R_star||: 8.542152051096907e-16
error for scale = |s-s_star|: 4.440892098500626e-16
error for shift = ||b-b_star||: 1.666962068746921e-16


*A teraz stosujemy funkcję `generalProcrustes`*

In [40]:
R_star,s_star,b_star = generalProcrustes(C,Cp)

*i również sprawdzamy ...*

In [41]:
print('R-R_star:',R-R_star)
print('error for rotation matrix ||R-R_star||:',norm(R-R_star))
print('error for scale = |s-s_star|:',abs(s-s_star))
print('error for shift = ||b-b_star||:',norm(b-b_star))

R-R_star: [[-2.22044605e-16 -1.11022302e-16  2.35699940e-16]
 [ 0.00000000e+00 -1.11022302e-16 -6.78892305e-17]
 [-8.50796550e-17 -2.33745655e-17 -4.44089210e-16]]
error for rotation matrix ||R-R_star||: 5.82339474391554e-16
error for scale = |s-s_star|: 4.440892098500626e-16
error for shift = ||b-b_star||: 1.1822950248236328e-16


**Koniec Rozwiązania**

#### M23L: Pytanie (P.1)
Tworzymy chmurę $C'=RC$ przez rotację o macierzy $R=[r_x,r_y,r_z]$, tj. $\tp{R}R=I_3,$ $\det{R}=1$. Modyfikujemy transformację zamieniając miejscami kolumny macierzy $R$ i  otrzymujemy macierz $R'\eqd[r_y,r_z,r_x].$ Czy macierz $R'$ jest macierzą obrotu? <br>Uzasadnij swoją odpowiedź.

In [73]:
import math
import numpy as np

C = randn(3,100); c_avg = np.average(C,axis=1)

theta = math.pi
R = [[math.cos(theta), -math.sin(theta), 0],
      [math.sin(theta),  math.cos(theta), 0],
      [0, 0, 1]]

R_prim = [[-math.sin(theta), 0,math.cos(theta)],
    [math.cos(theta), 0, math.sin(theta)],
    [0, 1, 0]]

R = np.array(R)
R_prim = np.array(R_prim)

print("Czy R_prim to macierz jednostkowa? \n", np.allclose(np.dot(R_prim, R_prim.transpose()), np.eye(3)))
print("Wyznacznik R_prim to: ", det(R_prim))


Czy R_prim to macierz jednostkowa? 
 True
Wyznacznik R_prim to:  1.0


Tak, ponieważ kolumny są zamieniane cyklicznie, co powoduje, że wyznacznik macierzy będzie równy 1 nawet po przesunięciu kolumn. Jest to również macierz ortogonalna, czyli R_prim spełnia obydwa zadane warunki na bycie macierzą obrotu.

#### M23L: Pytanie (P.2)

Niech $C\inm{3}{1000}$ będzie chmurą o $n=1000$ punktach w 3D losowanych z rozkładu Gaussowskiego. Wykonujemy obrót, skalowanie i przesunięcie według formuły:
$$
c'_i =
3\cdot
\left[
\begin{array}{ccc}
\frac{1}{2} & \frac{\sqrt{3}}{2} &  0\\
\frac{\sqrt{3}}{2} & -\frac{1}{2} & 0\\
0 & 0 & 1
\end{array}
  \right]
  c_i +
\left[
\begin{array}{c}
1\\
1\\
1
\end{array}
  \right],\ i=0,\dots,999
$$
Zauważmy, że powyższa transformacja nie jest rotacją. Dlaczego? Zastosuj formuły Procrustesa dla chmur $C,C'$. Czy powyższe transformacje zostały odzyskane?

In [81]:
R = np.array([[1/2, sq3/2, 0],[sq3/2,-1/2,0],[0,0,1]])


print("Czy podana macierz to macierz jednostkowa? \n", np.allclose(np.dot(R, R.transpose()), np.eye(3)))
print("Wyznacznik macierzy to: ", det(R))
print("\nGdyby macierz była macierzą obrotu to obróciłaby chmurę punktów o kąty:\n", np.arccos(1/2), np.arccos(-1/2), np.arcsin(sq3/2), "\n Kąty obrotu nie są sobie równe, więc nie może być to macierz obrotu.")
print("\nPonad to wyznacznik macierzy jest zbliżony do -1 , co oznacza, że nie jest to macierz obrotu, a macierz odbicia lustrzanego.")

Czy podana macierz to macierz jednostkowa? 
 True
Wyznacznik macierzy to:  -0.9999999999999999

Gdyby macierz była macierzą obrotu to obróciłaby chmurę punktów o kąty:
 1.0471975511965979 2.0943951023931957 1.0471975511965976 
 Kąty obrotu nie są sobie równe, więc nie może być to macierz obrotu.

Ponad to wyznacznik macierzy jest zbliżony do -1 , co oznacza, że nie jest to macierz obrotu, a macierz odbicia lustrzanego.


In [91]:
import numpy as np
from scipy.linalg import svd

C = np.random.normal(size=(1000, 3))

transform_matrix = np.array([
    [0.5, np.sqrt(3)/2, 0],
    [np.sqrt(3)/2, -0.5, 0],
    [0, 0, 1]
])

C_prime = 3 * np.dot(C, transform_matrix) + np.array([1, 1, 1])

centroid_C = np.mean(C, axis=0)
centroid_C_prime = np.mean(C_prime, axis=0)

C_centered = C - centroid_C
C_prime_centered = C_prime - centroid_C_prime

A = np.dot(C_centered.T, C_prime_centered)

U, S, Vt = svd(A)

R = np.dot(Vt.T, U.T)

scale = np.sum(S) / np.sum(C_centered ** 2)

t = centroid_C_prime - scale * np.dot(centroid_C, R)

C_transformed = scale * np.dot(C, R) + t

print("Macierz rotacji R:")
print(R)
print("\nSkalowanie:")
print(scale)
print("\nWektor przesunięcia t:")
print(t)

difference = np.linalg.norm(C_transformed - C_prime)
print("\nBłąd dopasowania między C_transformed a C_prime:")
print(difference)


Macierz rotacji R:
[[ 5.00000000e-01  8.66025404e-01  5.55192720e-17]
 [ 8.66025404e-01 -5.00000000e-01 -1.66131059e-16]
 [-3.33357193e-16  4.06294122e-17  1.00000000e+00]]

Skalowanie:
2.9999999999999996

Wektor przesunięcia t:
[1. 1. 1.]

Błąd dopasowania między C_transformed a C_prime:
1.1649377152629387e-13


Metoda Procrustesa nie była w stanie dokładnie odzyskać początkowej transformacji, zgodnie z oczekwaniami, ponieważ początkowe przekształcenie zawierało nie tylko rotację i przesunięcie, ale także odbicie oraz nierównomierne skalowanie. Metoda Procrustesa ma na celu dopasowanie dwóch chmur punktów za pomocą jedynie rotacji, przesunięcia i jednolitego skalowania. Nie jest jednak w stanie odzwierciedlić odbicia ani uwzględnić nierównomiernego skalowania. Dlatego też odzyskana transformacja może różnić się od początkowej.

####*Dowód uogólnionego twierdzenia Procrustesa*

Ten nietrywialny dowód opiera sie na kilku własnościach, z których dwie nie są oczywiste:
1. *Własność centroidu* $c\inv{M}$ zbioru $X=\{x_1,\dots,x_N\}\subset\bb{R}^M:$<br>
$$
c = \frac{1}{N}\sum_{i=1}^Nx_i \iff c = \arg\min_{a\inv{M}}\sum_{i=1}^N\|x_i-a\|^2_2
$$<br>
  *Dowód:* Niech $f_X(a)\eqd\ds\sum_{i=1}^N\|x_i-a\|^2_2$. Wtedy
$$
f_X(a) = \sum_{i=1}^N\tp{x}_ix_i -2\tp{a}\sum_{i=1}^Nx_i+N\cdot\tp{a}a \lra
\od{f_x(a)}{a} = 0_M -2\sum_{i=1}^Nx_i+2N\cdot a
$$<br>
  Minimalny punkt $c$ funkcji $f_X(a)$ musi być punktem stacjonarnym teh funkcji, tj. jej gradient musi się w nim zerować:
$$
\left.\od{f_x(a)}{a}\right|_{a=c} = 0_M \iff c = \frac{1}{N}\sum_{i=1}^Nx_i\quad
$$<br>
  Co więcej $c$ jest jedynym punktem stacjonarnym, a więc nie tylko dostatecznym ale i warunkiem koniecznym na minimum funkcji $f_X(a).\quad\Box$
1. *Symetria śladu złożenia macierzy $X,Y\inm{M}{M}$:*
$$
X,Y\inm{M}{M} \lra \tr{XY}=\tr{YX}
$$<br>
  *Dowód:*
  $$
  \begin{array}{l}
  \tr{XY} = \ds\sum_{i=1}^M(XY)_{ii}=\sum_{i=1}^M\sum_{k=1}^MX_{ik}Y_{ki} =
  \sum_{i=1}^M\sum_{k=1}^MY_{ki}X_{ik}
  \\[3pt]\ds\underbrace{=}_{i\leftrightarrow k}
  \sum_{k=1}^M\sum_{i=1}^MY_{ik}X_{ki} = \sum_{i=1}^M\sum_{k=1}^MY_{ik}X_{ki} =
  \sum_{i=1}^M(YX)_{ii} = \tr{YX}\quad\Box
  \end{array}
  $$
1. *Liniowość:* $\tr{(\alpha X+\beta Y)} =
\alpha\tr{X}+\beta\tr{Y}$
1. *Inwariantność względem transpozycji:* $X\inm{M}{M} \lra \tr{\tp{X}}=\tr{X}$
1. *Ślad iloczynu zewneętrznego jest iloczynem skalarnym*: $x,y\inv{M}\lra\tr{x\tp{y}} =\tp{x}y$
1. *Kwadrat normy macierzy to ślad iloczynu zewnętrznego tej macierzy:* $X\inm{M}{N}\lra\|X\|^2 = \tr{X\tp{X}}$:

  *Dowód:*
  $$
  X=[x_1,\dots,x_N], x_i\inv{M} \lra \tr{X\tp{X} }= \tr{\sum_{i=1}^Nx_i\tp{x}_i} =
  \sum_{i=1}^N\tr{x_i\tp{x}_i} = \sum_{i=1}^N\tp{x}_ix_i = \sum_{i=1}^N\|x_i\|^2 = \|X\|^2
  $$

*Obserwacje wstępne:*<br>
Problem minimalizacji funkcji błędu $\cl{E}(R,s,b)\eqd\ds\min_{s,R,b}\left\|sRC+b\tp{1}_N-C'\right\|^2$ dla $C,C'\inm{M}{N}$,
możemy sprowadzić do problemu $\min_{s,R}\left\|A-sRB\right\|^2$ w kilku krokach:
1. Zauważmy, że przy ustalonym $s,R$ optymalny wektor $b$ minimalizuje błąd kwadratowy dla zbioru wektorów znajdujących się w kolumnach macierzy $C'-sRC$.
$$
b^{\ast}=\arg\min_b\|C'-sRC-b\tp{1}_N\|^2 = \arg\min_b\sum_{i\in[N]}\|(c'_i-sRc_i)-b\|^2 \lra
b^{\ast}=\frac{1}{N}\sum_{i\in[N]} (c'_i-sRc_i) = \ov{c}'-sR\ov{c}
$$
W takim razie optymalne $b$ musi być centroidem tego zbioru, tj. $b^{\ast} = \ov{c}'-sR\ov{c}$.
2. Zastępując w funkcji błędu $\cl{E}$ parametr $b$ jego optymalną wartością względem $s,R$, definiujemy macierze $A,B$, jak następuje:
$$
\begin{array}{l}
b = \ov{c}'-sR\ov{c},\
A \eqd C'-\ov{c}'\tp{1}_N,\
B \eqd C-\ov{c}\tp{1}_N\\[2pt]
\lra \cl{E}(R,s,b) = \left\|sRC+b\tp{1}_N-C'\right\|^2 = \left\|A-sRB\right\|^2
\end{array}
$$

*Zasadnicza część dowodu:*<br>
1. Norma w postaci *trace*:
$$\|A-sRB\|_F^2=\tr{A\tp{A}}+s^2\cdot\tr{B\tp{B}}-2s\cdot\tr{A\tp{B}\tp{R}}$$
1. Równoważny problem *trace* (przy ustalonym $s\in\bb{R}_+$):
$$R^*=\arg\max_{R:\tp{R}R=I_m}\tr{A\tp{B}\tp{R}}$$
1. Dekompozycja SVD: $$A\tp{B}\xeq{svd}{U\Sigma \tp{V}}$$
1. Macierz ortogonalna $Z\eqd \tp{V}\tp{R}U:$
$$\tr{A\tp{B}\tp{R}}=\tr{U\Sigma \tp{V}\tp{R}}=\tr{\Sigma \tp{V}\tp{R}U} =\tr{\Sigma Z}$$
1. Górne ograniczenie:
$$|Z_{ij}|\leq 1 \lra \tr{\Sigma Z}=\sum_i\sigma_i Z_{ii}\leq \sum_i\sigma_i.$$
1. *Konkluzja 1:*
$R=U\tp{V} \lra Z=I_m$ maksymalizuje $\tr{\Sigma Z}= \tr{A\tp{B}\tp{R}}$ i wtedy przy dowolnym $s\in\bb{R}_+$ wyrażenie  $\|A-sRB\|_F^2$ przyjmuje wartość minimalną równą:
$$\tr{A\tp{A}}+s^2\cdot\tr{B\tp{B}}-2s\cdot\tr{\Sigma}$$
1. *Konkluzja 2:* Minimalna wartość błędu modelowania $\|A-sR^{\ast}B\|_F^2$ przyjmowana jest dla współczynnika skalowania $$s^{\ast}=\frac{\tr{\Sigma}}{\tr{B\tp{B}}}$$


### Geometryczna interpretacja dekompozycji SVD

Wartości singularne $\Sigma$ i macierze ortogonalne $U,V$ w dekompozycji SVD dla macierzy $A\inm{m}{n}$ mają ciekawa interpretację geometryczną. Mianowicie rozważmy obraz $S'$ sfery jednostkowej $S(0_n;1)$ przy odwzorowaniu nieosobliwym $A:\bb{R}^n\ra\bb{R}^n:$
$$
S'\eqd\{Ax|\ x\inv{n},\ \tp{x}x=1\}
$$
Można łatwo sprawdzić, że zbiór $S'$ ma symetrię środkową, tj. $x\in S'$ wtt $-x\in S'.$
Można też znaleźć punkty w $S'$ najbliższe i najdalsze względem punktu zerowego. Po prostu znajdujemy stacjonarne punkty funkcj Lagrange'a  $L(x,\lambda)=\|Ax\|^2-\lambda\|x\|^2=\tp{x}(\tp{A}A)x-\lambda\tp{x}x$:
$$
  \od{L(x,\lambda)}{x}=2\tp{A}{A}x-2\lambda x=0_n\lra \tp{A}Ax=\lambda x \text{ oraz } \|Ax\|^2=\lambda\|x\|^2=\lambda
$$
Opis wszystkich punktów stacjonarnych tej funkcji faktycznie prowadzi do EVD macierzy $\tp{A}A$:
$\tp{A}A\overset{evd}{=}V\Sigma^2\tp{V}$.

Mamy więc:
- punkt najdalszy
$y_{max}=Av_1=U\Sigma\tp{V}v_1=U\Sigma e_1 = U(\sigma_1e_1)=\sigma_1u_1$,
- podobnie punkt najbliższy $y_{min}=Av_n=U\Sigma\tp{V}v_n=\sigma_nu_n$
- oraz punkty siodłowe $y_i=Av_i=U\Sigma\tp{V}v_i=\sigma_iu_i$ dla $1<i<n$.

W takim razie możemy scharakteryzowac kształt $S'$ będący obrazem sfery jednostkowej przy transformacji $A$ - jest hiper-elipsoidą, w której:
- półosie mają kierunki zgodne (lub przeciwne) z lewostronnymi wektorami singularnymi macierzy $A$, tj. z wektorami  $u_i$, $i=1,\dots,n$,
- długości tych półosi sa równe  $\sigma_i$, $i=1,\dots,n$.


#### M23L: Pytanie SVD-AX

Czym są półosie hiperelipsoidy w terminach algebraicznych?

Półosie hiperelipsoidy w terminach algebraicznych są opisane przy użyciu macierzy kowariancji. Hiperelipsoida jest wielowymiarowym odpowiednikiem elipsoidy w przestrzeni, gdzie każdy wymiar jest reprezentowany przez półosie elipsoidy.

Jeśli mamy hiperelipsoidę w n-wymiarowej przestrzeni, to półosie hiperelipsoidy są związane z macierzą kowariancji (lub macierzą kowariancji) danej jako Σ (Sigma). Macierz kowariancji to symetryczna macierz kwadratowa o rozmiarze n x n, gdzie n jest liczbą wymiarów przestrzeni.

Półosie hiperelipsoidy odpowiadają pierwiastkom (wartościom własnym) tej macierzy kowariancji. Pierwiastki te można przedstawić jako d1, d2, ..., dn, gdzie d1 >= d2 >= ... >= dn. Są to długości półosi hiperelipsoidy wzdłuż odpowiednich osi współrzędnych.

Ogólnie, jeśli Σ to macierz kowariancji, to półosie hiperelipsoidy wzdłuż poszczególnych osi współrzędnych są d1, d2, ..., dn, gdzie d1, d2, ..., dn to pierwiastki (wartości własne) macierzy Σ. Ich wartości i wzajemne stosunki opisują, jak hiperelipsoida jest rozciągana i obracana w przestrzeni.